apiVersion: v1
kind: Service
metadata:
  name: testapp-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - protocol: TCP
    name: http
    port: 8111
    targetPort: 8080
  externalIPs:
  - 192.168.56.105
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: sam-docker-testapp
          image: 876724398547.dkr.ecr.us-east-2.amazonaws.com/sam-docker-testapp:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name: regcred